# External gems
gems:
#  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

#excerpt_separator: <!--more-->

# Site settings
title: Talorojekti
subtitle: "Tarinaa yksikerroksisen 121m² puutalon rakentamisesta Kaarinaan"
email: email@vesanieminen.com
name: Vesa Nieminen
description: > 
  Tarinaa yksikerroksisen 121m² puutalon rakentamisesta Kaarinaan
baseurl: "/talorojekti" # the subpath of your site, e.g. /blog/
url: "talorojekti.vesanieminen.com" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
#logo: "assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
#jekyll-archives: 
#  enabled: 
#    - categories
#    - tags
#  layout: 'archive'
#  permalinks:
#    category: '/category/:name/'
#    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: talorojekti

# Google analytics
ga_tracking_id: "UA-67250864-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: 2015-09-syyskuu
    desc: ""

  - cat: 2015-08-elokuu
    desc: ""

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
  - name: Twitter
    icon: twitter
    username: "@vesanieminen"
    url: https://twitter.com/vesanieminen
    desc: Seuraa minua Twitterissä
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - name: Facebook
    icon: facebook
    username: vesa.nieminen
    url: https://www.facebook.com/vesa.nieminen
    desc: Pyydä minua kaveriksi
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - name: GitHub
    icon: github
    username: vesanieminen
    url: https://github.com/vesanieminen
    desc: Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - name: LinkedIn
    icon: linkedin
    username: vnieminen
    url: https://fi.linkedin.com/in/vnieminen
    desc: Connect with me on LinkedIn
    share_url: //www.linkedin.com/shareArticle
    share_title: ?mini=true
    share_link: "&amp;url="

  - name: Google+
    icon: google-plus
    username: vesa.nieminen 
    url: https://plus.google.com/102863562871172858236
    desc: Add me to your Circles
    share_url: //plus.google.com/share
    share_title: ?title=
    share_link: "&amp;url="

  - name: YouTube
    icon: youtube
    username: 
    url: 
    desc: Subscribe on YouTube
    share_url: 
    share_title: 
    share_link:

  - name: Instagram
    icon: instagram
    username: 
    url: 
    desc: Follow me on Instagram
    share_url: 
    share_title: 
    share_link:

  - name: Pinterest
    icon: pinterest
    username: 
    url: 
    desc: Follow me on Pinterest
    share_url: 
    share_title: 
    share_link:

  - name: SoundCloud
    icon: soundcloud
    username: 
    url: 
    desc: Follow me on SoundCloud
    share_url: 
    share_title: 
    share_link:

  - name: Tumblr
    icon: tumblr
    username: 
    url: 
    desc: Follow me on Tumblr
    share_url: 
    share_title: 
    share_link:

  - name: Steam
    icon: steam
    username: 
    url: 
    desc: Friend me on Steam
    share_url: 
    share_title: 
    share_link:

  - name: Dribbble
    icon: dribbble
    username: 
    url: 
    desc: Follow me on Dribble

  - name: Vimeo
    icon: vimeo-square
    username: 
    url: 
    desc: Follow me on Vimeo

  - name: Vine
    icon: vine
    username: 
    url: 
    desc: Follow me on Vine
